config/routes.rb
ArchibotApp::Application.routes.draw do
  resources :architects do
    resources :buildings
  end

  resources :users do
    resources :trips
  end

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#delete"

  root "splash#index"

  get "/buildings", to: "buildings#index"

  post "/architects/:architect_id/buildings/:id/favorite", to: "buildings#favorite", as: "favorite"
  post "/architects/:architect_id/buildings/:id/unfavorite", to: "buildings#unfavorite", as: "unfavorite"

  post "/architects/:id/favorite", to: "architects#favorite", as: "favorite_architect"
  post "/architects/:id/unfavorite", to: "architects#unfavorite", as: "unfavorite_architect"

end

app/models/architect.rb
# == Schema Information
#
# Table name: architects
#
#  id        :integer          not null, primary key
#  name      :string(255)
#  year_born :integer
#  year_died :integer
#  style     :string(255)
#

class Architect < ActiveRecord::Base
  validates :name, {presence: true, uniqueness: true}
  validates :style, {presence: true}
  has_many :buildings, dependent: :destroy 
  has_and_belongs_to_many :users

  def self.search(query)
    if query
      where('name LIKE ?', query)
    else
      all
    end
  end

end

app/controllers/architects_controller.rb
  class ArchitectsController < ApplicationController
  include MethodHelper
  before_action :load_architect, only: [:show, :edit, :destroy, :favorite, :unfavorite, :update]

  def index
    @items = Architect.search(params[:search])
    @architects = Architect.all
  end

  def show
    find_buildings(@architect)
    if @architect.description != nil
      @description = @architect.description
    else
      @description = get_description(@architect)
      @architect.description = @description
    end
  end

  def new
    @architect = Architect.new
  end

  def create
    @architect = Architect.new(user_params)
    @architect.save
    if @architect.save
      redirect_to architect_path(@architect)
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    @architect.update (user_params)
    redirect_to architect_path
  end

  def destroy
    if current_user.is_admin?
      @architect.destroy
      redirect_to architects_path
    else
      render nothing: true, status: 401
    end
  end

  def favorite
    current_user.architects << @architect
    redirect_to architect_path
  end

  def unfavorite
    current_user.architects.delete(@architect)
    redirect_to architect_path
  end

  def search
    @items = Architect.search(params[:search])
  end

private 

  def load_architect
    @architect = Architect.find(params[:id])
  end

  def user_params
    params.require(:architect).permit(:name, :style, :year_born, :year_died)
  end

end

app/views/architects/_form.html.erb
<%= form_for @architect do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :style %><br>
  <%= f.text_field :style %><br>

  <%= f.label "Year Born (year founded for firms)" %><br>
  <%= f.text_field :year_born %><br>

  <%= f.label :year_died %><br>
  <%= f.text_field :year_died %><br>
  
  <%= f.submit %>
<%end%>

app/views/architects/edit.html.erb
<h2>Archibot</h2>

Edit this architect

<%= render "form" %>

<%=link_to("Back to all architects", architects_path) %>

<br>
<br>

app/views/architects/index.html.erb
<h2>Architects</h2>
<p>Click on the name of an architect or firm to see the info page. Add an architect to the database to see some buildings they designed that you might want to check out!</p>
<br>

<%unless @items == nil%>
  <% @items.each do |architect| %>
    <p>
    <%=link_to("#{architect.name}", architect)%><br>
    </p>
  <%end%>

<%else%>
  <%@architects.each do |architect| %>
    <p>
    <%=link_to("#{architect.name}", architect)%><br>
    </p>
  <%end%>
<%end%>

<br>
<%=link_to("Add a new architect", new_architect_path)%>
<br>
<br>
<br>

app/views/architects/new.html.erb
<h2>Archibot</h2>

<p>Add a new architect</p>

<% if @architect.errors.count > 0 %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @architect.errors.messages.each do |field,error| %>
        <li><%= "#{field.capitalize} #{error.first}!" %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= render "form" %>

<%=link_to("Back to all architects", architects_path) %>

<br>
<br>

app/views/architects/show.html.erb
<br>
<div class="architect-title">
  <h2><%= @architect.name %></h2>
  <h3><%= @architect.style %></h3>
</div>
<div class="architect-links">
  <%=link_to("Buildings by this architect in the database", architect_buildings_path(@architect.id)) %>
  <br>
  <%=link_to("Add a building to this architect", new_architect_building_path(@architect.id)) %>
  <br>
  <% if current_user %>
  <%=link_to("Edit this architect", edit_architect_path) %>
  <%end%>
  <br>
  <% if current_user %>
    <% unless current_user.architects.include?(@architect)%>
      <%= link_to "favorite", favorite_architect_path, method: :post %>
    <% else %>
      <%= link_to "unfavorite", unfavorite_architect_path, method: :post %>
    <% end %>
  <% end %>
</div>
<br>
<div class="architect-description"><%= @description %></div>
<br>
Suggested buildings to add:
<ul>
  <% @buildings_designed.each do |result| %>
    <li><%= result %></li>
  <% end %>
</ul>

<% if current_user && current_user.is_admin? %>
  <%= form_tag architect_path(@architect), method: "delete" do %>
    <%= submit_tag("Delete") %>
  <% end %>
<%end%>

<br>
<br>

<%=link_to("Back to all architects", architects_path) %>
<br>
<br>