config/routes.rb
ArchibotApp::Application.routes.draw do
  resources :architects do
    resources :buildings
  end

  resources :users do
    resources :trips
  end

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#delete"

  root "splash#index"

  get "/buildings", to: "buildings#index"

  post "/architects/:architect_id/buildings/:id/favorite", to: "buildings#favorite", as: "favorite"
  post "/architects/:architect_id/buildings/:id/unfavorite", to: "buildings#unfavorite", as: "unfavorite"

  post "/architects/:id/favorite", to: "architects#favorite", as: "favorite_architect"
  post "/architects/:id/unfavorite", to: "architects#unfavorite", as: "unfavorite_architect"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  validates :first_name, {presence: true}
  validates :last_name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  has_secure_password
  has_and_belongs_to_many :buildings
  has_and_belongs_to_many :architects
  has_many :trips
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :load_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
    if current_user == nil
      redirect_to login_path
    else
      if current_user.buildings != nil 
        @favorites = current_user.buildings 
      end
      if current_user.architects != nil 
        @favorite_architects = current_user.architects
      end
      if current_user.trips != nil
        @trips = current_user.trips
      end
    end
  end

  def edit
    render(:edit)
  end

  def update
    if @user = current_user || current_user.is_admin?
      @update_worked = @user.update(user_params)
      if @update_worked
        redirect_to user_path(@user)
      else
        render(:edit)
      end
    else
      render nothing: true, status: 401
    end
  end

  def destroy
    if @user = current_user || current_user.is_admin?
      session[:user_id] = nil
      @user.destroy
      redirect_to root_path
    else
      render nothing: true, status: 401
    end
  end

private

  def load_user
    return @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>

  <%= f.submit @user.id.nil? ? "Join!" : "Save Changes" %>
<% end %>

app/views/users/edit.html.erb
Edit your info


<%= render "form" %>

<%= link_to("Cancel" , user_path) %>
<br>
<br>

app/views/users/new.html.erb
<h2>Join Archibot</h2>

<%= render "form" %>

<% if @user.errors.count > 0 %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><%= "#{field.capitalize} #{error.first}!" %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<br>

app/views/users/show.html.erb
<h2>Welcome <%=@user.first_name%>!</h2>
<h3><%=link_to("Browse the database", architects_path)%></h3>

<p>Full Name:
  <%=@user.first_name%><%=@user.last_name%></p>

<p>Email Address:
  <%=@user.email%></p>

<p>Favorite Buildings</p>
<ul>
  <% @favorites.each do |building| %>
    <li><%=link_to("#{building.name}", architect_building_path(building.architect.id, building.id))%></li>
  <%end%>
</ul>

<p>Favorite Architects</p>
<ul>
<% @favorite_architects.each do |architect| %>
<li><%=link_to("#{architect.name}", architect_path(architect.id))%></li>
<%end%>
</ul>
<br>

<p>Trips</p>
<ul>
  <% @trips.each do |trip| %>
  <li><%= link_to(trip.title, user_trip_path(current_user, trip))%></li>
  <%end%>
</ul>

<% if current_user %>
  <%= link_to("Edit My Info", edit_user_path(@user))%>
  <%= form_tag user_path(@user), method: "delete" do%>
    <%= submit_tag("Delete Account")%>
  <%end%>
<%end%>

<br>
<br>