config/routes.rb
ArchibotApp::Application.routes.draw do
  resources :architects do
    resources :buildings
  end

  resources :users do
    resources :trips
  end

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#delete"

  root "splash#index"

  get "/buildings", to: "buildings#index"

  post "/architects/:architect_id/buildings/:id/favorite", to: "buildings#favorite", as: "favorite"
  post "/architects/:architect_id/buildings/:id/unfavorite", to: "buildings#unfavorite", as: "unfavorite"

  post "/architects/:id/favorite", to: "architects#favorite", as: "favorite_architect"
  post "/architects/:id/unfavorite", to: "architects#unfavorite", as: "unfavorite_architect"

end

app/models/building.rb
# == Schema Information
#
# Table name: buildings
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  address      :string(255)
#  year_built   :integer
#  photo_url    :string(255)
#  latitude     :float
#  longitude    :float
#  architect_id :integer
#

class Building < ActiveRecord::Base
  validates :name, {presence: true, uniqueness: true}
  validates :address, {presence: true}
  validates :architect, {presence: true}
  geocoded_by :address
  after_validation :geocode
  belongs_to :architect
  has_and_belongs_to_many :users
  has_and_belongs_to_many :trips

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  include MethodHelper
  before_action :load_architect, only: [:index, :show, :edit, :create, :new, :destroy]
  before_action :load_building, only: [:show, :edit, :destroy, :update]

  def index
    @buildings = Building.where(architect_id: params[:architect_id])
  end

  def show
    find_entries(@building)
    @map = get_map(@building,@buildings_nearby)
    pull_photos(@building)
    if @building.description != nil
      @description = @building.description
    else
      @description = get_building_description(@building)
      @building.description = @description
    end
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(user_params)
    @building.architect = @architect
    @building_description = get_building_description(@building)
    if @building.description == nil
      @building.description = @building_description
      @building.save
    else
      @building.save
    end
    if @building.save
      redirect_to architect_building_path(@architect, @building)
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    @building.update(user_params)
    redirect_to architect_building_path
  end

  def destroy
    if current_user.is_admin?
      @architect = @building.architect
      @building.destroy
      redirect_to architect_path(@architect)
    else
      render nothing: true, status: 401
    end
  end

  def favorite
    @building = Building.find(params[:id])
    current_user.buildings << @building
    redirect_to architect_building_path
  end

  def unfavorite
    @building = Building.find(params[:id])
    current_user.buildings.delete(@building)
    redirect_to architect_building_path
  end

private

  def user_params
    params.require(:building).permit(:name, :address, :year_built, :photo_url)
  end

  def load_architect
    @architect = Architect.find(params[:architect_id])
  end

  def load_building
    @building = Building.find(params[:id])
  end
end

app/views/buildings/_form.html.erb
<%= form_for [@architect, @building] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :address %><br>
  <%= f.text_field :address %><br>

  <%= f.label :year_built %><br>
  <%= f.text_field :year_built %><br>

  <%= f.label :photo_url %><br>
  <%= f.url_field :photo_url %><br>

  <%= f.submit %>
<%end%>

app/views/buildings/edit.html.erb
<h2>Edit this Building</h2>

<%= render "form" %>
<br>
<br>

app/views/buildings/index.html.erb
<h2><%=@architect.name%></h2>

Buildings
<ul>
  <%@buildings.each do |building| %>
    <li><%=link_to("#{building.name}", architect_building_path(@architect,building)) %>
    <br/>
      <%if @user = admin?%>
        <%=link_to("edit", edit_architect_building_path(@architect, building))%>
        <%=form_tag architect_building_path(@architect, building), method: "delete" do %>
        <%=submit_tag("Delete")%>
        <%end%>
      <%end%>
    <%end%>
  </ul>
<br>
<p>Add a building to this architect to see it on a map, see other buildings nearby, and see instagram photos taken at that location.</p>
<%=link_to("Add a building to this architect", new_architect_building_path(@architect.id))%>
<br>
<br>
<br>

app/views/buildings/new.html.erb
<h2>Add a Building for this Architect</h2>

<% if @building.errors.count > 0 %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @building.errors.messages.each do |field,error| %>
        <li><%= "#{field.capitalize} #{error.first}!" %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= render "form" %>

<br>
<br>

app/views/buildings/show.html.erb
<div class="building-title">
  <h2><%= @building.name%></h2>
  <h3>Year Constructed: <%= @building.year_built%></h3>
  <h3>Architect: <%=link_to("#{@building.architect.name}", architect_path(@building.architect.id) )%></h3>
</div>
<div class="favorite">
  <% if current_user %>
    <% if !current_user.buildings.include?(@building)%>
      <%= link_to "favorite", favorite_path, method: :post %>
    <% else %>
      <%= link_to "unfavorite", unfavorite_path, method: :post %>
    <% end %>
  <% end %>
  <% if current_user %>
    <%= link_to "Create Trip", new_user_trip_path(current_user) %>
    <% end %>
</div>

<div class="bigphoto"><img src="<%= @building.photo_url %>"></div>

<div class="building-description">
  <p><%=@building.description%></p>
</div>

<div class="closebldgs">
  <div class="map">
    <img src="<%= @map %>">
  </div class="map">
  <div class="bldglist">
    <span>Other buildings in the database close to this one:</span>
      <ul>
        <% if !@buildings_nearby[0].nil? %>
          <% @buildings_nearby.each do |building| %>
            <li><%=link_to("#{building.name}", architect_building_path(building.architect.id, building.id)) %></li>
          <%end%>
          <%else%>
          <p>There are no buildings close by in the database</p>
        <%end%>
      </ul>
  </div>
</div>
<br>
<% if current_user %>
<%=link_to("edit", edit_architect_building_path(@architect,@building)) %>
<%end%>
<% unless @location == nil %>
  <br>Some photos taken near this location, from instagram:<br>
  <% @photos.each do |photo| %>
    <div class="insta">
    <img src = "<%=photo%>">
    </div class="insta">
  <%end%>
  <%else%>
    <p>There are no available photos from this location</p>
<%end%>
<br>
<br>
<% if @user = admin? %>
  <%= form_tag architect_building_path(@architect, @building), method: "delete" do %>
  <%= submit_tag("Delete") %>
<% end %>
<%end%>
<br>
<br>