config/routes.rb
ArchibotApp::Application.routes.draw do
  resources :architects do
    resources :buildings
  end

  resources :users do
    resources :trips
  end

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#delete"

  root "splash#index"

  get "/buildings", to: "buildings#index"

  post "/architects/:architect_id/buildings/:id/favorite", to: "buildings#favorite", as: "favorite"
  post "/architects/:architect_id/buildings/:id/unfavorite", to: "buildings#unfavorite", as: "unfavorite"

  post "/architects/:id/favorite", to: "architects#favorite", as: "favorite_architect"
  post "/architects/:id/unfavorite", to: "architects#unfavorite", as: "unfavorite_architect"

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  include MethodHelper

  def index
    @photos = get_photos
  end
end

app/views/splash/index.html.erb
<h1>Welcome to Archibot!</h1>

<div class="login_panel">
  <p><%= link_to "View the collection", architects_path %><p>
  <br>
  <p><%= link_to "Join Archibot", new_user_path %></p>
  <p><%= link_to "Login", "/login" %></p>
  <br>
</div>

<div class="smallpics">
  <% @photos.each do |photo| %>
    <img src = "<%=photo%>">
  <%end%>
</div class="smallpics">

<%= form_tag architects_path, :method => 'get' do %>
  <div class="search">
  <%= text_field_tag :search, nil, :placeholder => "Search architects here" %>
  <%= submit_tag "Search", :name => nil %>
  </div>
<% end %>

<p>Check out the github page <a href="http://kdoyne.github.io/archibot">here</a> for more info.</p>